# Generated by Django 2.2 on 2021-09-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belcon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='account_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='routing_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b2a',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b2b',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b2c',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step2b4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step4_a',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step4_b',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='step4_c',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='uploaded_documents',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
