# Generated by Django 3.1.3 on 2021-09-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belcon_app', '0002_auto_20210901_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='uploaded_documents',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='direct_deposit_check',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='id_1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='id_2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
