# Generated by Django 3.1.3 on 2021-09-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belcon_app', '0004_auto_20210907_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='step2',
            field=models.CharField(blank=True, default='None', max_length=255, null=True),
        ),
    ]
